"""A real multi-turn agentic loop against the served model.

The --reasoning-budget fix was validated on SINGLE turns (n=20 replays of one
captured request). This runs an actual conversation: the model's tool calls are
executed for real, the results are fed back, and it continues until the task is
done or a turn limit is hit.

The question: does the budget hold across a conversation, or does the failure
reappear once history accumulates?

Safety: every tool is confined to a disposable working directory. Shell commands
are refused if they touch anything outside it, escalate privileges, or reach the
network. This runs model-generated commands, so the sandbox is the point.

    python3 agent_loop.py [workdir] [max_turns]

Point it at a server with GLM53_URL if it is not on localhost:8090.
"""
import json
import os
import re
import shutil
import subprocess
import sys
import time
import urllib.request

URL = os.environ.get("GLM53_URL", "http://127.0.0.1:8090") + "/v1/chat/completions"
WORK = os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else "./agent_sandbox")
MAX_TURNS = int(sys.argv[2]) if len(sys.argv) > 2 else 12

# Refused outright. This executes text generated by a language model; the
# sandbox is not a formality.
FORBIDDEN = re.compile(
    r"\b(sudo|su|doas|chmod\s+[0-7]*7[0-7]*|chown|mkfs|dd\s|shutdown|reboot|"
    r"systemctl|kill|pkill|crontab|ssh|scp|rsync|curl|wget|nc|ncat|pip\s+install|"
    r"uv\s+tool|apt|apt-get|yum|dnf|brew|docker|git\s+push|git\s+remote)\b"
    r"|>\s*/(?!tmp)|\brm\s+-rf\s+/|~\/|\$HOME|/etc/|/usr/|/var/")

# Absolute paths under a home directory are allowed ONLY inside the sandbox.
# This used to be a hardcoded author-specific path in the regex above, which
# silently refused every command for anyone else.
_HOME_ABS = re.compile(r"/home/[^\s\"\';|&)]*")


def safe(cmd):
    if FORBIDDEN.search(cmd):
        return False, "refused: touches something outside the sandbox"
    for m in _HOME_ABS.finditer(cmd):
        if not os.path.abspath(m.group(0)).startswith(WORK):
            return False, f"refused: absolute path outside the sandbox ({m.group(0)})"
    return True, ""


def run_shell(args):
    cmd = args.get("command", "")
    ok, why = safe(cmd)
    if not ok:
        return f"REFUSED by sandbox: {why}\ncommand was: {cmd}"
    try:
        # shell=True is deliberate: this tool IS "run a shell command", and the
        # model emits pipes, redirects and &&. A list form would break it.
        # Defence in depth, since this executes model-generated text:
        #   - denylist above rejects privilege escalation, network and system paths
        #   - cwd and HOME both point at the disposable sandbox, so ~ resolves there
        #   - minimal PATH, no inherited environment
        #   - 60s timeout
        # The sandbox directory is deleted and recreated on every run.
        # The pre-made venv comes first so `python` and `pytest` just work. The
        # first run of this harness spent ten turns hunting for an interpreter,
        # which measured the denylist rather than the model.
        env = {"PATH": f"{WORK}/.venv/bin:/usr/local/bin:/usr/bin:/bin",
               "HOME": WORK, "LANG": "C.UTF-8", "TMPDIR": WORK,
               "VIRTUAL_ENV": f"{WORK}/.venv"}
        r = subprocess.run(cmd, shell=True, cwd=WORK, capture_output=True,
                           text=True, timeout=60, env=env)
        out = (r.stdout or "") + (r.stderr or "")
        return f"exit={r.returncode}\n{out[:3000]}" or "(no output)"
    except subprocess.TimeoutExpired:
        return "command timed out after 60s"
    except Exception as e:
        return f"error: {e}"


def _resolve(path):
    p = os.path.abspath(os.path.join(WORK, path))
    if not p.startswith(WORK):
        raise ValueError("path escapes the sandbox")
    return p


def write_file(args):
    try:
        p = _resolve(args.get("path", ""))
        os.makedirs(os.path.dirname(p), exist_ok=True)
        open(p, "w").write(args.get("content", ""))
        return f"wrote {args['path']} ({len(args.get('content',''))} bytes)"
    except Exception as e:
        return f"error: {e}"


def read_file(args):
    try:
        return open(_resolve(args.get("path", ""))).read()[:3000]
    except Exception as e:
        return f"error: {e}"


def list_files(args):
    try:
        out = []
        for root, _, files in os.walk(WORK):
            for f in files:
                out.append(os.path.relpath(os.path.join(root, f), WORK))
        return "\n".join(sorted(out)[:100]) or "(empty)"
    except Exception as e:
        return f"error: {e}"


def fn(name, desc, props, req):
    return {"type": "function", "function": {"name": name, "description": desc,
            "parameters": {"type": "object", "properties": props,
                           "required": req, "additionalProperties": False}}}


TOOLS = [
    fn("run_shell", "Run a shell command in the project root. Non-interactive only.",
       {"command": {"type": "string"}}, ["command"]),
    fn("write_file", "Create or overwrite a file with the given content.",
       {"path": {"type": "string"}, "content": {"type": "string"}}, ["path", "content"]),
    fn("read_file", "Read a file's contents.", {"path": {"type": "string"}}, ["path"]),
    fn("list_files", "List all files in the project.", {}, []),
]
DISPATCH = {"run_shell": run_shell, "write_file": write_file,
            "read_file": read_file, "list_files": list_files}

SYSTEM = ("You are an autonomous coding agent operating on a real repository. "
          "Use the provided tools to take actions. Prefer a tool call over prose "
          "whenever an action is required. Work one step at a time; the harness "
          "will feed you each tool result and let you continue.")

TASK = (
    "Build a Python CLI called `logstat` in this directory.\n"
    "1. Create pyproject.toml targeting Python 3.11+.\n"
    "2. Implement logstat/cli.py reading newline-delimited JSON logs with keys "
    "ts, level, msg, duration_ms.\n"
    "3. Report count/min/max/mean/p95 of duration_ms.\n"
    "4. Support --level and --format table|json.\n"
    "5. A malformed line must print a clear error to stderr and exit 2, never a traceback.\n"
    "6. Generate sample.jsonl with 20 records across 3 levels.\n"
    "7. Write pytest tests covering happy path, empty file, malformed line, --level, --format json.\n"
    "8. Run the tests with `python -m pytest` and fix anything that fails.\n"
    "\nThe environment is ready: `python` and `pytest` are already installed and "
    "on PATH. Do NOT install anything and do NOT look for an interpreter — just "
    "build the project.\n"
    "When everything passes, reply with DONE and a one-line summary.\n"
    "Make reasonable choices and proceed. Do not ask questions."
)

if os.path.isdir(WORK):
    shutil.rmtree(WORK)
os.makedirs(WORK)

# Provision before starting. Network access is refused inside the sandbox by
# design, so whatever the agent needs must already exist.
print("provisioning sandbox venv with pytest ...", flush=True)
subprocess.run([sys.executable, "-m", "venv", os.path.join(WORK, ".venv")], check=True)
subprocess.run([os.path.join(WORK, ".venv", "bin", "pip"), "install", "-q", "pytest"],
               check=True)
print("ready", flush=True)

msgs = [{"role": "system", "content": SYSTEM},
        {"role": "user", "content": TASK}]

print(f"sandbox: {WORK}")
print(f"{'turn':<5} {'prompt_tok':>11} {'completion':>11} {'reason_ch':>10} "
      f"{'finish':<12} {'wall':>8}  calls", flush=True)

exhausted = 0
t_start = time.monotonic()
for turn in range(1, MAX_TURNS + 1):
    body = {"model": "glm-5.3-flash", "max_tokens": 16384, "tools": TOOLS,
            "messages": msgs}
    req = urllib.request.Request(URL, data=json.dumps(body).encode(),
                                 headers={"Content-Type": "application/json"})
    t0 = time.monotonic()
    try:
        d = json.load(urllib.request.urlopen(req, timeout=1800))
    except Exception as e:
        print(f"{turn:<5} ERROR {type(e).__name__}: {e}", flush=True)
        break
    dt = time.monotonic() - t0
    ch = d["choices"][0]
    m = ch["message"]
    u = d.get("usage", {})
    calls = m.get("tool_calls") or []
    rc = m.get("reasoning_content") or ""
    fr = ch.get("finish_reason")
    content = m.get("content") or ""

    if fr == "length" and not calls and len(content.strip()) < 40:
        exhausted += 1

    print(f"{turn:<5} {u.get('prompt_tokens',0):>11} {u.get('completion_tokens',0):>11} "
          f"{len(rc):>10} {str(fr):<12} {dt:>7.1f}s  "
          f"{[c['function']['name'] for c in calls]}", flush=True)

    asst = {"role": "assistant", "content": content}
    if rc:
        asst["reasoning_content"] = rc
    if calls:
        asst["tool_calls"] = calls
    msgs.append(asst)

    if not calls:
        if "DONE" in content.upper():
            print(f"\nAgent reported DONE on turn {turn}")
        else:
            print(f"\nNo tool calls and no DONE — stopping. content: {content[:200]!r}")
        break

    for c in calls:
        name = c["function"]["name"]
        try:
            args = json.loads(c["function"]["arguments"])
        except Exception:
            args = {}
        result = DISPATCH.get(name, lambda a: "unknown tool")(args)
        if name == "run_shell":
            print(f"        $ {args.get('command','')[:110]}", flush=True)
        msgs.append({"role": "tool", "tool_call_id": c.get("id", "x"),
                     "content": str(result)[:4000]})

print(f"\ntotal wall: {(time.monotonic()-t_start)/60:.1f} min")
print(f"budget-exhausted turns: {exhausted}")
print("\nfiles produced:")
for root, _, files in os.walk(WORK):
    for f in sorted(files):
        rel = os.path.relpath(os.path.join(root, f), WORK)
        print(f"  {rel} ({os.path.getsize(os.path.join(root,f))} bytes)")
